auth-server:
  base-url: ${AUTH_SERVER_URL}

spring:
  security:
    oauth2:
      client:
        registration:
          auth-server:
            client-id: ${ADMIN_CLIENT_ID}
            client-secret: ${ADMIN_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI}
            scope: openid, profile
          m2m-client:
            client-id: ${M2M_CLIENT_ID}
            client-secret: ${M2M_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: client:manage
            provider: auth-server
        provider:
          auth-server:
            issuer-uri: ${AUTH_SERVER_URL}
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/admindb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    kr.it.rudy: INFO
