spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/admindb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    kr.it.rudy: INFO
